name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Build site
        run: pnpm eleventy
      - name: SSH setup
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
          echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
          chmod -R 700 ~/.ssh
      - name: Rsync deploy
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          rsync -avz -e ssh --delete _site/ ${DEPLOY_USER}@${DEPLOY_HOST}:/var/www/bodil.lol/
